version: '3.8'

services:
  laravel:
    image: cosmospham/laravel-dev-container:latest
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/laravel
    ports:
      - "8000:8000"
      - "5173:5173"  # Vite dev server
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    depends_on:
      mysql:
        condition: service_healthy
    command: sleep infinity

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

volumes:
  mysql-data: